### **Installing libraries**

In [ ]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.13/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.3)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)

### **Importing libraries**

In [ ]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

### **Search for Target protein**

### Target search for **Leucine-rich repeat serine/threonine-protein kinase 2**

In [ ]:
# Target search for
target = new_client.target
target_query = target.search('lrrk2')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Mus musculus,Leucine-rich repeat serine/threonine-protein k...,16.0,False,CHEMBL2010622,"[{'accession': 'Q5S006', 'component_descriptio...",SINGLE PROTEIN,10090
1,[],Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,15.0,False,CHEMBL1075104,"[{'accession': 'Q5S007', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Mus musculus,Protein cereblon/Leucine-rich repeat serine/th...,14.0,False,CHEMBL4802028,"[{'accession': 'Q5S006', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
3,[],Homo sapiens,Protein cereblon/Leucine-rich repeat serine/th...,14.0,False,CHEMBL5465219,"[{'accession': 'Q5S007', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
4,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/Leu...,13.0,False,CHEMBL5465239,"[{'accession': 'Q5S007', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
5,[],Mus musculus,von Hippel-Lindau disease tumor suppressor/Leu...,13.0,False,CHEMBL5465252,"[{'accession': 'Q5S006', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090

Select and retrieve bioactivity data for Human Leucine-rich repeat serine/threonine-protein kinase 2. (first entry)<br>
We will assign the second entry (which corresponds to the target protein, Human
lrrk2, single protein) to the selected_target variable

In [ ]:
selected_target = targets.target_chembl_id[1]
selected_target

'CHEMBL1075104'

Here, we will retrieve only bioactivity data for Human lrrk2 (CHEMBL1075104) that are reported as pChEMBL values.

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
df = pd.DataFrame.from_dict(res)

In [ ]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6180232,[],CHEMBL1772597,Inhibition of purified N-terminal GST-tagged L...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,13.2
1,None,None,6180234,[],CHEMBL1772599,Inhibition of purified N-terminal GST-tagged L...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,4.1
2,None,None,7989381,[],CHEMBL1937075,Inhibition of human LRRK2,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,16.0
3,None,None,10840480,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,13.0
4,None,None,10840481,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6776,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303277,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181858,Inhibition of LRRK2 G2019S mutant (unknown ori...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.008
6777,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303278,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181858,Inhibition of LRRK2 G2019S mutant (unknown ori...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.011
6778,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303279,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181858,Inhibition of LRRK2 G2019S mutant (unknown ori...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.126
6779,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303416,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181902,Inhibition of LRRK2 activity in human A549 cel...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,118.0
6780,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303417,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181902,Inhibition of LRRK2 activity in human A549 cel...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,48.9

In [ ]:
df.to_csv('LRRK2_01_bioactivity_data_raw.csv', index=False)

**Copying files to Google Drive**<br>
Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [ ]:
#! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data’: File exists

In [ ]:
! cp LRRK2_01_bioactivity_data_raw.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 9638
-rw------- 1 root root 9868400 Aug 24 05:54 LRRK2_01_bioactivity_data_raw.csv

In [ ]:

! ls

gdrive	LRRK2_01_bioactivity_data_raw.csv  sample_data

Taking a glimpse of the bioactivity_data.csv file that we've just created.

In [ ]:

! head LRRK2_01_bioactivity_data_raw.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,6180232,[],CHEMBL1772597,Inhibition of purified N-terminal GST-tagged LRRK2 G2019S mutant autophosphorylation activity using [gamma32-P]ATP,B,Q5S007,G2019S,BAO_0000190,BAO_0000019,assay format,Cc1cc(N/N=C/c2ccc(O)c(O)c2)nc2ccccc12,,,CHEMBL1770059,Bioorg Med Chem Lett,2011,"{'bei': '16.63', 'le': '0.30', 'lle': '1.48', 'sei': '6.28'}",,CHEMBL1771409,,CHEMBL1771409,4.88,0,http://www.openphacts.org/units/Nanomolar,1420091,=,1,1,=,,IC50,nM,,13200.0,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,uM,UO_0000065,,13.2
,,6180234,[],CHEMBL1772599,Inhibition of purified N-terminal GST-tagged LRRK2 G2019S mutant autophosphorylation activity using myelin basic protein as substrate,B,Q5S007,G2019S,BAO_0000190,BAO_0000019,assay format,Cc1cc(N/N=C/c2ccncc2)nc2ccccc12,,,CHEMBL1770059,Bioorg Med Chem Lett,2011,"{'bei': '20.54', 'le': '0.37', 'lle': '2.01', 'sei': '10.74'}",,CHEMBL1771411,,CHEMBL1771411,5.39,0,http://www.openphacts.org/units/Nanomolar,1420093,=,1,1,=,,IC50,nM,,4100.0,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,uM,UO_0000065,,4.1
,,7989381,[],CHEMBL1937075,Inhibition of human LRRK2,B,,,BAO_0000190,BAO_0000357,single protein format,C[C@@H]1CCNC(=O)c2cc3ccc(C(=O)Nc4nc5ccccc5n4CCCN(C)C)cc3n21,,,CHEMBL1933005,Bioorg Med Chem Lett,2012,"{'bei': '17.00', 'le': '0.31', 'lle': '3.91', 'sei': '9.26'}",,CHEMBL1933288,,CHEMBL1933288,7.80,0,http://www.openphacts.org/units/Nanomolar,1567059,=,1,1,=,,IC50,nM,,16.0,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,16.0
,,10840480,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK293 cells using nictide and [gamma32]ATP as substrate,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1cc(C(=O)N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc2c(n1)N(C)c1ccccc1C(=O)N2C,,,CHEMBL2010643,Bioorg Med Chem Lett,2012,"{'bei': '13.82', 'le': '0.26', 'lle': '4.45', 'sei': '8.10'}",,CHEMBL2012582,,CHEMBL2012582,7.89,0,http://www.openphacts.org/units/Nanomolar,1633218,=,1,1,=,,IC50,nM,,13.0,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,13.0
,,10840481,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK293 cells using nictide and [gamma32]ATP as substrate,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1cc(N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc(Cl)c(Nc2ccccc2S(=O)(=O)C(C)C)n1,,,CHEMBL2010643,Bioorg Med Chem Lett,2012,"{'bei': '13.20', 'le': '0.26', 'lle': '3.09', 'sei': '7.88'}",,CHEMBL509032,TAE-684,CHEMBL509032,8.11,0,http://www.openphacts.org/units/Nanomolar,1633217,=,1,1,=,,IC50,nM,,7.8,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,7.8
,,10840482,[],CHEMBL2015542,Inhibition of LRRK2 G2019S mutant expressed in HEK293 cells using nictide and ATP as substrate,B,Q5S007,G2019S,BAO_0000190,BAO_0000219,cell-based format,COc1cc(C(=O)N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc2c(n1)N(C)c1ccccc1C(=O)N2C,,,CHEMBL2010643,Bioorg Med Chem Lett,2012,"{'bei': '14.41', 'le': '0.27', 'lle': '4.78', 'sei': '8.44'}",,CHEMBL2012582,,CHEMBL2012582,8.22,0,http://www.openphacts.org/units/Nanomolar,1633218,=,1,1,=,,IC50,nM,,6.0,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,6.0
,,10840483,[],CHEMBL2015542,Inhibition of LRRK2 G2019S mutant expressed in HEK293 cells using nictide and ATP as substrate,B,Q5S007,G2019S,BAO_0000190,BAO_0000219,cell-based format,COc1cc(N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc(Cl)c(Nc2ccccc2S(=O)(=O)C(C)C)n1,,,CHEMBL2010643,Bioorg Med Chem Lett,2012,"{'bei': '13.37', 'le': '0.27', 'lle': '3.19', 'sei': '7.98'}",,CHEMBL509032,TAE-684,CHEMBL509032,8.21,0,http://www.openphacts.org/units/Nanomolar,1633217,=,1,1,=,,IC50,nM,,6.1,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,6.1
,,10840484,[],CHEMBL2015543,Inhibition of LRRK2 A2016T mutant expressed in HEK293 cells using nictide and ATP as substrate,B,Q5S007,A2016T,BAO_0000190,BAO_0000219,cell-based format,COc1cc(C(=O)N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc2c(n1)N(C)c1ccccc1C(=O)N2C,,,CHEMBL2010643,Bioorg Med Chem Lett,2012,"{'bei': '9.83', 'le': '0.18', 'lle': '2.17', 'sei': '5.76'}",,CHEMBL2012582,,CHEMBL2012582,5.61,0,http://www.openphacts.org/units/Nanomolar,1633218,=,1,1,=,,IC50,nM,,2450.0,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,2450.0
,,10840485,[],CHEMBL2015543,Inhibition of LRRK2 A2016T mutant expressed in HEK293 cells using nictide and ATP as substrate,B,Q5S007,A2016T,BAO_0000190,BAO_0000219,cell-based format,COc1cc(N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc(Cl)c(Nc2ccccc2S(=O)(=O)C(C)C)n1,,,CHEMBL2010643,Bioorg Med Chem Lett,2012,"{'bei': '11.45', 'le': '0.23', 'lle': '2.01', 'sei': '6.83'}",,CHEMBL509032,TAE-684,CHEMBL509032,7.03,0,http://www.openphacts.org/units/Nanomolar,1633217,=,1,1,=,,IC50,nM,,93.3,CHEMBL1075104,Homo sapiens,Leucine-rich repeat serine/threonine-protein kinase 2,9606,,,IC50,nM,UO_0000065,,93.3

###**Handling missing data**

If any compounds has missing value for the standard_value and canonical_smiles column then drop it.

In [ ]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_2373/3852201246.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6180232,[],CHEMBL1772597,Inhibition of purified N-terminal GST-tagged L...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,13.2
1,None,None,6180234,[],CHEMBL1772599,Inhibition of purified N-terminal GST-tagged L...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,4.1
2,None,None,7989381,[],CHEMBL1937075,Inhibition of human LRRK2,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,16.0
3,None,None,10840480,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,13.0
4,None,None,10840481,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6776,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303277,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181858,Inhibition of LRRK2 G2019S mutant (unknown ori...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.008
6777,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303278,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181858,Inhibition of LRRK2 G2019S mutant (unknown ori...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.011
6778,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303279,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181858,Inhibition of LRRK2 G2019S mutant (unknown ori...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.126
6779,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303416,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181902,Inhibition of LRRK2 activity in human A549 cel...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,118.0
6780,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303417,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181902,Inhibition of LRRK2 activity in human A549 cel...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,48.9

In [ ]:
len(df2.canonical_smiles.unique())

3783

In [ ]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6180232,[],CHEMBL1772597,Inhibition of purified N-terminal GST-tagged L...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,13.2
1,None,None,6180234,[],CHEMBL1772599,Inhibition of purified N-terminal GST-tagged L...,B,Q5S007,G2019S,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,4.1
2,None,None,7989381,[],CHEMBL1937075,Inhibition of human LRRK2,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,16.0
3,None,None,10840480,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,13.0
4,None,None,10840481,[],CHEMBL2015541,Inhibition of wild-type LRRK2 expressed in HEK...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,nM,UO_0000065,None,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6722,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303223,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181857,Inhibition of recombinant wild type GST-LRRK2 ...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.83
6723,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303224,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181857,Inhibition of recombinant wild type GST-LRRK2 ...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.081
6724,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303225,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181857,Inhibition of recombinant wild type GST-LRRK2 ...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.006
6725,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303226,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181857,Inhibition of recombinant wild type GST-LRRK2 ...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.006
6726,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29303227,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6181857,Inhibition of recombinant wild type GST-LRRK2 ...,B,None,None,BAO_0000190,...,Homo sapiens,Leucine-rich repeat serine/threonine-protein k...,9606,None,None,IC50,uM,UO_0000065,None,0.071

**Data pre-processing of the bioactivity data**<br>
Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame

In [ ]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL1771409,Cc1cc(N/N=C/c2ccc(O)c(O)c2)nc2ccccc12,13200.0
1,CHEMBL1771411,Cc1cc(N/N=C/c2ccncc2)nc2ccccc12,4100.0
2,CHEMBL1933288,C[C@@H]1CCNC(=O)c2cc3ccc(C(=O)Nc4nc5ccccc5n4CC...,16.0
3,CHEMBL2012582,COc1cc(C(=O)N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc2c...,13.0
4,CHEMBL509032,COc1cc(N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc(Cl)c(N...,7.8
...,...,...,...
6722,CHEMBL6192175,CC(C)n1ccc(Nc2nc(N(C)[C@@H](C)C3CC3)c3cc[nH]c3...,830.0
6723,CHEMBL6190367,Cn1cc(Nc2nc(N[C@H]3CCc4ccccc43)c3nc[nH]c3n2)cn1,81.0
6724,CHEMBL6190371,CC(C)n1cc(Nc2nc(N[C@H]3CCc4ccccc43)c3nc[nH]c3n...,6.0
6725,CHEMBL6191498,CC(C)n1cc(Nc2nc(N[C@@H](C)C3CC3)c3c(C#N)c[nH]c...,6.0
6726,CHEMBL6190327,C[C@H](Nc1nc(Nc2cn(C)nn2)nc2[nH]cc(C#N)c12)C1CC1,71.0

In [ ]:
df3.to_csv('LRRK2_02_bioactivity_data_preprocessed.csv', index=False)

###**Labeling compounds as either being active, inactive or intermediate**

The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be active while those greater than 10,000 nM will be considered to be inactive. As for those values in between 1,000 and 10,000 nM will be referred to as intermediate.

In [ ]:
df4 = pd.read_csv('LRRK2_02_bioactivity_data_preprocessed.csv')

In [ ]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [ ]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL1771409,Cc1cc(N/N=C/c2ccc(O)c(O)c2)nc2ccccc12,13200.0,inactive
1,CHEMBL1771411,Cc1cc(N/N=C/c2ccncc2)nc2ccccc12,4100.0,intermediate
2,CHEMBL1933288,C[C@@H]1CCNC(=O)c2cc3ccc(C(=O)Nc4nc5ccccc5n4CC...,16.0,active
3,CHEMBL2012582,COc1cc(C(=O)N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc2c...,13.0,active
4,CHEMBL509032,COc1cc(N2CCC(N3CCN(C)CC3)CC2)ccc1Nc1ncc(Cl)c(N...,7.8,active
...,...,...,...,...
3778,CHEMBL6192175,CC(C)n1ccc(Nc2nc(N(C)[C@@H](C)C3CC3)c3cc[nH]c3...,830.0,active
3779,CHEMBL6190367,Cn1cc(Nc2nc(N[C@H]3CCc4ccccc43)c3nc[nH]c3n2)cn1,81.0,active
3780,CHEMBL6190371,CC(C)n1cc(Nc2nc(N[C@H]3CCc4ccccc43)c3nc[nH]c3n...,6.0,active
3781,CHEMBL6191498,CC(C)n1cc(Nc2nc(N[C@@H](C)C3CC3)c3c(C#N)c[nH]c...,6.0,active
3782,CHEMBL6190327,C[C@H](Nc1nc(Nc2cn(C)nn2)nc2[nH]cc(C#N)c12)C1CC1,71.0,active

**Save DataFrame to CSV**

In [ ]:
df5.to_csv('LRRK2_Bioactivity_preprocessed_data.csv', index=False)

In [ ]:
! zip LRRK2.zip *.csv

updating: LRRK2_01_bioactivity_data_raw.csv (deflated 97%)
updating: LRRK2_02_bioactivity_data_preprocessed.csv (deflated 82%)
updating: LRRK2_03_bioactivity_data_curated.csv (deflated 83%)
  adding: LRRK2_Bioactivity_preprocessed_data.csv (deflated 83%)

In [ ]:
! ls -l

ls: cannot access 'drive': Transport endpoint is not connected
total 10976
d????????? ? ?    ?          ?            ? drive
drwx------ 5 root root    4096 Aug 24 06:18 gdrive
-rw-r--r-- 1 root root 9868400 Aug 24 05:46 LRRK2_01_bioactivity_data_raw.csv
-rw-r--r-- 1 root root  267229 Aug 24 06:01 LRRK2_02_bioactivity_data_preprocessed.csv
-rw-r--r-- 1 root root  295224 Aug 24 06:01 LRRK2_03_bioactivity_data_curated.csv
-rw-r--r-- 1 root root  295224 Aug 24 06:18 LRRK2_Bioactivity_preprocessed_data.csv
-rw-r--r-- 1 root root  488198 Aug 24 06:18 LRRK2.zip
drwxr-xr-x 1 root root    4096 Aug 20 13:29 sample_data

In [ ]:
! cp LRRK2_Bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data"

LRRK2_01_bioactivity_data_raw.csv  LRRK2_Bioactivity_preprocessed_data.csv

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/